"""Document type labels, keyword lists, and confidence thresholds."""

from __future__ import annotations

DOCUMENT_TYPES: list[str] = [
    "invoice",
    "contract",
    "resume",
    "report",
    "letter",
    "form",
    "unknown",
]

# Minimum confidence to accept the primary classification;
# below this threshold the document is labelled "unknown".
CONFIDENCE_THRESHOLD: dict[str, float] = {
    "invoice": 0.40,
    "contract": 0.40,
    "resume": 0.40,
    "report": 0.35,
    "letter": 0.35,
    "form": 0.40,
    "unknown": 0.0,
}

# Keyword signatures per document type used by the rule-based fallback.
KEYWORD_SIGNATURES: dict[str, list[str]] = {
    "invoice": [
        "invoice",
        "bill to",
        "invoice number",
        "invoice date",
        "payment due",
        "amount due",
        "subtotal",
        "tax",
        "total",
        "remit to",
        "purchase order",
        "po number",
        "unit price",
        "qty",
        "quantity",
        "line item",
    ],
    "contract": [
        "agreement",
        "whereas",
        "hereinafter",
        "party",
        "parties",
        "obligations",
        "terms and conditions",
        "governing law",
        "effective date",
        "termination",
        "indemnify",
        "indemnification",
        "liability",
        "confidentiality",
        "breach",
        "clause",
        "consideration",
        "witnesseth",
        "executed",
    ],
    "resume": [
        "resume",
        "curriculum vitae",
        "cv",
        "experience",
        "education",
        "skills",
        "objective",
        "summary",
        "work history",
        "employment",
        "references",
        "gpa",
        "degree",
        "university",
        "college",
        "bachelor",
        "master",
        "phd",
    ],
    "report": [
        "executive summary",
        "introduction",
        "methodology",
        "findings",
        "conclusion",
        "recommendations",
        "appendix",
        "abstract",
        "background",
        "scope",
        "analysis",
        "results",
        "discussion",
        "references",
    ],
    "letter": [
        "dear",
        "sincerely",
        "regards",
        "yours truly",
        "to whom it may concern",
        "re:",
        "subject:",
        "enclosed",
        "please find",
        "i am writing",
        "thank you for",
        "best regards",
    ],
    "form": [
        "please complete",
        "fill in",
        "check all that apply",
        "signature",
        "date of birth",
        "social security",
        "full name",
        "address",
        "phone number",
        "email address",
        "please print",
        "instructions",
        "required",
        "optional",
        "section",
    ],
}

# Structural feature weights per document type
STRUCTURAL_WEIGHTS: dict[str, dict[str, float]] = {
    "invoice": {"has_tables": 2.0, "has_numbers": 1.5, "short_doc": 1.0},
    "contract": {"multi_page": 1.5, "has_headers": 1.0, "long_paragraphs": 1.0},
    "resume": {"has_bullet_lists": 1.5, "multi_section": 1.0, "has_dates": 1.0},
    "report": {"multi_page": 1.0, "has_headers": 1.5, "has_figures": 1.0},
    "letter": {"single_page": 1.5, "short_paragraphs": 1.0},
    "form": {"has_blanks": 2.0, "has_checkboxes": 2.0, "short_lines": 1.0},
}
